### ISSUE TITLE
Not updating price of plugin - aka not showing sale !

### ISSUE THREAD

**Issue by hb20c** [CGeorges/unrealsales-tracker#20]
I've added a couple asset links to my wish list now, and they are not updating to show the current marketplace sale. E.g. Ultra Dynamic sky is showing up in the tracker as $29.99. However on the Marketplace it is currently on sale at 50% discount at $14.99.

**Comment by CGeorges** [comment]
Hi @hb20c the prices are updated everyday at 8 in the morning, the sale has started today in the afternoon so it wasn't picked up by UnrealSales, it will reflect tomorrow morning.

**Comment by hb20c** [comment]
thanks for the response Georges- works great!
