### ISSUE TITLE
CRITICAL ISSUE - Wishlist bugged out completely on adding an item

### ISSUE THREAD

**Issue by UncleFred** [CGeorges/unrealsales-tracker#27]
Hi! I've encountered a marketplace item that iff added to a wishlist, will completely bug out the tracker. [Here](https://imgur.com/a/uowToV2) is what I see.

This is the item that bugs out the list:
https://www.unrealengine.com/marketplace/en-US/product/epic-zen-garden

**Comment by CGeorges** [comment]
Hi @UncleFred can you post a picture with your Console open?

To do so, open unrealsales page and press F12. Make sure that in the window the tab Console is selected then refresh the page and take a screenshot.

**Comment by UncleFred** [comment]
Hi Georges. You can actually replicate this issue yourself by adding the item to your wishlist. I tried a fresh account, added the item, and it bugged out. Seems like it's only this one marketplace item though. I have hundreds of other items listed in other accounts without any problem.

**Comment by CGeorges** [comment]
Hi @UncleFred I'm investigating the issue right now.

**Comment by CGeorges** [comment]
Thank you @UncleFred for the help to investigate this. The issue had been resolved and the application should not crash anymore, the issue was that the product Epic Zen Garden didn't have a category set in the marketplace and UnrealSales was always expecting one.

**Comment by UncleFred** [comment]
That's great. Thank you.
