### ISSUE TITLE
Wishlist Prices stoped updating

### ISSUE THREAD

**Issue by Robertofgjr** [CGeorges/unrealsales-tracker#31]
Has been a few days now since my wishlist stoped updating completely. Not sure if its across the whole service or just me.

**Comment by CGeorges** [comment]
Hi @Robertofgjr can you please give more information on how did it stop updating? when you add new products they don't show up? or the prices are not updated?

**Comment by Robertofgjr** [comment]
For a few days now my wishlist dosnt show updated prices from the market. It looks like its not being updated anymore.

**Comment by squarecrowgames** [comment]
Seeing the same thing.

I know there's an expected ([FAQ](https://www.unrealsales.io/tracker/faq)) day lag between when an asset goes on sale on the marketplace where it gets refreshed here, but I watched [an asset](https://www.unrealengine.com/marketplace/en-US/product/old-man-animset) already in my wish-list go on sale at-least 4 days ago and have been checking in on it daily and still not seeing it as "for sale" here yet.

My last email from unrealsales-tracker was from 3/23/21 and I've started wondering if there was an email problem. Looks like it's a refresh problem instead.

**Comment by Robertofgjr** [comment]
Yeah, its stopped for more than a month for me now, wondering if that is account bound. My lists are not updating price changes at all anymore. I know that cause I check it almost everyday since I use the site to keep track of assets aswell, not only for checking prices.

**Comment by CGeorges** [comment]
Can you mail me to cgeorges89@gmail.com so I can search your account by email and figure out what is the problem with your account?

**Comment by UncleFred** [comment]
Hi Georges. I'm having the same issue. Looks like it stopped updating prices sometime in the last 2-3 weeks.

**Comment by UncleFred** [comment]
Hi CGeorges. Looks like the tracker is still not updating. Do you need me to email you account details or help in any way?

**Comment by CGeorges** [comment]
Thank you @UncleFred, I've identified the problem and working on a fix.

**Comment by CGeorges** [comment]
A fix had been deployed and prices are being refreshed as we speak,it might skip the emails today but everything should work fine starting tomorrow. Thank you @UncleFred for your help!

**Comment by UncleFred** [comment]
Thank you CGeorges. Looks great.
