### ISSUE TITLE
Login down

### ISSUE THREAD

**Issue by UncleFred** [CGeorges/unrealsales-tracker#43]
Seems to be putting up an error this morning.

**Comment by UncleFred** [comment]
Seems to have been resolved. Thank you,

**Comment by CGeorges** [comment]
Yes, Amazon AWS is suffering an outage. UnrealSales is built on top of their serverless services
https://www.theverge.com/2021/12/7/22822332/amazon-server-aws-down-disney-plus-ring-outage

Should be back on it's own once the outage is resolved.

**Comment by UncleFred** [comment]
Thanks for the update CGeorges.

Also, any chance we can get sorting options? For example, on the Black Friday sale, it would have been nice to sort by discount percentage. Price targets like the Amazon keepa or CamelCamel would be a welcome addition too.

Thanks for proving this service.
