### ISSUE TITLE
NO WAY TO UNSUBSCRIBE!

### ISSUE THREAD

**Issue by jjackson888** [CGeorges/unrealsales-tracker#51]
There is no way to unsubscribe. You say go to our profile but there is no profile menu. There is no way to get to a profile. There is no way to unsubscribe. I don't want any more emails.

**Comment by CGeorges** [comment]
Hi @jjackson888 please mail me to hello@vodoostudios.com from the email you've used to register and I will delete your account permanently.

We only send emails when one of your items in your wishlist is on sale, removing all items from your lists will have the same effect and you won't receive any emails from us.
